config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root 'records#search'

    resources :records do
      collection do
        get :export
        get :search
        put :load_csv
      end
    end

    namespace :divisions do
      get '/', action: :load_division_names
    end

    namespace :record_statistics do
      get '/', action: :index
    end

    resources :drugstores
    resources :hospitals
    resources :transports
    resources :people
  end
end

app/models/transport.rb
# frozen_string_literal: true

class Transport < Division
  has_many :hospital_transports, dependent: :destroy
  has_many :hospitals, through: :hospital_transports
  has_many :records, foreign_key: :division_id, inverse_of: :hospital, dependent: :destroy
end

app/controllers/transports_controller.rb
# frozen_string_literal: true

class TransportsController < ApplicationController
  before_action :set_transport, only: [:show, :edit, :update, :destroy]

  def index
    @transports = Transport.paginate(params)
  end

  def show
  end

  def new
    @transport = Transport.new
  end

  def edit
  end

  def create
    @transport = Transport.new(transport_params)

    respond_to do |format|
      if @transport.save
        format.html {redirect_to transports_url, notice: t('helpers.notice.create')}
        format.json {render :show, status: :created, location: @transport}
      else
        format.html {render :new, status: :unprocessable_content}
        format.json {render json: @transport.errors, status: :unprocessable_content}
      end
    end
  end

  def update
    respond_to do |format|
      if @transport.update(transport_params)
        format.html {redirect_to transports_url, notice: t('helpers.notice.update')}
        format.json {render :show, status: :ok, location: @transport}
      else
        format.html {render :edit, status: :unprocessable_content}
        format.json {render json: @transport.errors, status: :unprocessable_content}
      end
    end
  end

  def destroy
    @transport.destroy
    respond_to do |format|
      format.html {redirect_to transports_url, notice: t('helpers.notice.delete'), status: :see_other}
      format.json {head :no_content}
    end
  end

  private

  def set_transport
    @transport = Transport.find(params[:id])
  end

  def transport_params
    params.expect(transport: [:name])
  end
end

app/views/transports/_form.html.erb
<%= form_with(model: transport, local: true) do |form| %>
  <% if transport.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% transport.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row mb-3">
      <div class="col-4 col-md-2">
        <%= form.label :name %>
      </div>
      <div class="col-8 col-md-10">
        <%= form.text_field :name, class: 'form-control', required: true %>
      </div>
    </div>

    <div class="actions">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/transports/edit.html.erb
<h1>
  <%= t('helpers.title.edit', model: Transport.model_name.human) %>
</h1>

<%= render partial: 'partials/action' %>

<%= render 'form', transport: @transport %>

app/views/transports/index.html.erb
<h1>
  <%= t('helpers.title.list', models: Transport.model_name.human.pluralize(I18n.locale)) %>
</h1>

<%= paginate @transports %>
<table class='table table-bordered table-hover table-striped'>
  <thead>
  <tr>
    <th><%= Transport.human_attribute_name :name %></th>
  </tr>
  </thead>

  <tbody>
  <% @transports.each do |transport| %>
    <tr>
      <td><%= link_to transport.name, transport_path(transport) %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @transports %>

<br>

<%= link_to t('helpers.link.new'), new_transport_path %>

app/views/transports/new.html.erb
<h1>
  <%= t('helpers.title.new', model: Transport.model_name.human) %>
</h1>

<%= render partial: 'partials/action' %>

<%= render 'form', transport: @transport %>

app/views/transports/show.html.erb
<h1>
  <%= t('helpers.title.show', model: Transport.model_name.human) %>
</h1>

<%= render partial: 'partials/action' %>

<div class="container">
  <div class="row">
    <div class="col-4 col-sm-2">
      <%= Transport.human_attribute_name :name %>
    </div>
    <div class="col-8 col-sm-10">
      <%= @transport.name %>
    </div>
  </div>
</div>