config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root 'records#search'

    resources :records do
      collection do
        get :export
        get :search
        put :load_csv
      end
    end

    namespace :divisions do
      get '/', action: :load_division_names
    end

    namespace :record_statistics do
      get '/', action: :index
    end

    resources :drugstores
    resources :hospitals
    resources :transports
    resources :people
  end
end

app/models/person.rb
# frozen_string_literal: true

class Person < ApplicationRecord
  acts_as_paranoid

  has_many :records, dependent: :destroy

  validates :name, presence: true, uniqueness: {scope: [:relationship, :deleted_at]}
  validates :relationship, presence: true
end

app/controllers/people_controller.rb
# frozen_string_literal: true

class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def index
    @people = Person.paginate(params)
  end

  def show
  end

  def new
    @person = Person.new
  end

  def edit
  end

  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html {redirect_to people_url, notice: t('helpers.notice.create')}
        format.json {render :show, status: :created, location: @person}
      else
        format.html {render :new, status: :unprocessable_content}
        format.json {render json: @person.errors, status: :unprocessable_content}
      end
    end
  end

  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html {redirect_to people_url, notice: t('helpers.notice.update')}
        format.json {render :show, status: :ok, location: @person}
      else
        format.html {render :edit, status: :unprocessable_content}
        format.json {render json: @person.errors, status: :unprocessable_content}
      end
    end
  end

  def destroy
    @person.destroy
    respond_to do |format|
      format.html {redirect_to people_url, notice: t('helpers.notice.delete'), status: :see_other}
      format.json {head :no_content}
    end
  end

  private

  def set_person
    @person = Person.find(params[:id])
  end

  def person_params
    params.expect(person: [:name, :relationship])
  end
end

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row mb-3">
      <div class="col-4 col-sm-2">
        <%= form.label :name %>
      </div>
      <div class="col-8 col-sm-10">
        <%= form.text_field :name, class: 'form-control', required: true %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-4 col-sm-2">
        <%= form.label :relationship %>
      </div>
      <div class="col-8 col-sm-10">
        <%= form.text_field :relationship, class: 'form-control', required: true %>
      </div>
    </div>

    <div class="actions">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>
  <%= t('helpers.title.edit', model: Person.model_name.human) %>
</h1>

<%= render partial: 'partials/action' %>

<%= render 'form', person: @person %>

app/views/people/index.html.erb
<h1>
  <%= t('helpers.title.list', models: Person.model_name.human.pluralize(I18n.locale)) %>
</h1>

<%= paginate @people %>
<table class='table table-bordered table-hover table-striped'>
  <thead>
  <tr>
    <th><%= Person.human_attribute_name :name %></th>
    <th><%= Person.human_attribute_name :relationship %></th>
  </tr>
  </thead>

  <tbody>
  <% @people.each do |p| %>
    <tr>
      <td><%= link_to p.name, person_path(p) %></td>
      <td><%= tag.span p.relationship %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= paginate @people %>

<br>

<%= link_to t('helpers.link.new'), new_person_path %>

app/views/people/new.html.erb
<h1>
  <%= t('helpers.title.new', model: Person.model_name.human) %>
</h1>

<%= render partial: 'partials/action' %>

<%= render 'form', person: @person %>

app/views/people/show.html.erb
<h1>
  <%= t('helpers.title.show', model: Person.model_name.human) %>
</h1>

<%= render partial: 'partials/action' %>

<div class="container">
  <div class="row">
    <div class="col-4 col-sm-2">
      <%= Person.human_attribute_name :name %>
    </div>
    <div class="col-8 col-sm-10">
      <%= @person.name %>
    </div>
  </div>
  <div class="row">
    <div class="col-4 col-sm-2">
      <%= Person.human_attribute_name :relationship %>
    </div>
    <div class="col-8 col-sm-10">
      <%= @person.relationship %>
    </div>
  </div>
</div>