config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root 'records#search'

    resources :records do
      collection do
        get :export
        get :search
        put :load_csv
      end
    end

    namespace :divisions do
      get '/', action: :load_division_names
    end

    namespace :record_statistics do
      get '/', action: :index
    end

    resources :drugstores
    resources :hospitals
    resources :transports
    resources :people
  end
end

app/views/partials/_action.html.erb
<div class="mb-3">
  <%= link_to t('helpers.link.back'), {controller: controller.controller_name, action: :index},
              class: 'btn btn-info', role: :button %>
  <% case controller.action_name %>
  <% when 'edit' %>
    <%= link_to t('helpers.link.show'), {controller: controller.controller_name, action: :show},
                class: 'btn btn-info', role: :button %>
    <%= link_to t('helpers.link.delete'), {controller: controller.controller_name, action: :destroy},
                data: {turbo_method: :delete, turbo_confirm: t('helpers.notice.delete_confirm')},
                class: 'btn btn-danger', role: :button %>
  <% when 'show' %>
    <%= link_to t('helpers.link.edit'), {controller: controller.controller_name, action: :edit},
                class: 'btn btn-info', role: :button %>
    <%= link_to t('helpers.link.delete'), {controller: controller.controller_name, action: :destroy},
                data: {turbo_method: :delete, turbo_confirm: t('helpers.notice.delete_confirm')},
                class: 'btn btn-danger', role: :button %>
  <% end %>
</div>

app/views/partials/_locale.html.erb
<div class="container text-end">
  <% I18n.available_locales.reject {|l| l == I18n.locale}.each do |locale| %>
    <%= link_to image_tag("#{locale}.png", size: '36x36'),
                url_for(params.permit(:locale).merge(locale: locale)) %>
  <% end %>
</div>

app/views/partials/_menu.html.erb
<%= render partial: 'partials/locale' %>

<div class="container">
  <div class="row text-center bg-primary header">
    <div class="col-md-3 col-4">
      <%= link_to t('text.top.top_page'), root_path %>
    </div>
    <div class="col-md-3 col-4">
      <%= link_to Record.model_name.human, records_path %>
    </div>
    <div class="col-md-3 col-4">
      <%= link_to t('text.statistics.statistics'), record_statistics_path %>
    </div>
    <div class="col-md-3 col-4">
     <%= link_to Person.model_name.human, people_path %>
    </div>
    <div class="col-md-3 col-4">
      <%= link_to Hospital.model_name.human, hospitals_path %>
    </div>
    <div class="col-md-3 col-4">
      <%= link_to Drugstore.model_name.human, drugstores_path %>
    </div>
    <div class="col-md-3 col-4">
      <%= link_to Transport.model_name.human, transports_path %>
    </div>
  </div>
</div>

app/views/partials/_notices.html.erb
<% {notice: notice, alert: alert}.each do |key, val| %>
  <div class="<%= key %>">
    <% if val.is_a?(Array) %>
      <ul>
        <% val.each do |elem| %>
          <li><%= elem %></li>
        <% end %>
      </ul>
    <% else %>
      <%= val %>
    <% end %>
  </div>
<% end %>

app/views/partials/_stylesheets.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr@4.6.13/dist/themes/material_blue.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr@4.6.13/dist/plugins/monthSelect/style.min.css">