config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.map(&:to_s).join('|')}/ do
    root 'records#search'

    resources :records do
      collection do
        get :export
        get :search
        put :load_csv
      end
    end

    namespace :divisions do
      get '/', action: :load_division_names
    end

    namespace :record_statistics do
      get '/', action: :index
    end

    resources :drugstores
    resources :hospitals
    resources :transports
    resources :people
  end
end

app/models/record.rb
# frozen_string_literal: true

class Record < ApplicationRecord
  acts_as_paranoid

  validates :date, presence: true

  belongs_to :person
  belongs_to :division
  belongs_to :hospital, foreign_key: :division_id, inverse_of: :records, optional: true
  belongs_to :drugstore, foreign_key: :division_id, inverse_of: :records, optional: true
  belongs_to :transport, foreign_key: :division_id, inverse_of: :records, optional: true

  validates :cost, presence: true, numericality:
    {only_integer: true, greater_than_or_equal_to: 0}

  def create_self_and_transports!
    ret = []
    transaction do
      save!
      ret << self
      next unless (hospital_transports = hospital&.hospital_transports)

      hospital_transports.each do |ht|
        ret << Record.create!(person: person, date: date, cost: ht.transport_cost, division: ht.transport)
      end
    end
    ret
  end

  def create_self_and_transports
    create_self_and_transports!
  rescue ActiveRecord::RecordInvalid
    false
  end

  def self.annual_statistics(year = nil)
    year ||= Date.current.year
    year_date = Date.new(year.to_i)
    Record.where(date: year_date.all_year)
          .group(:person_id)
          .group(:division_id)
          .select('person_id, division_id, sum(cost) as sum_cost')
          .includes(:person)
          .includes(:division)
  end

  def division_type
    division&.type
  end
end

app/models/search/record.rb
# frozen_string_literal: true

module Search
  class Record < Search::Base
    attr_accessor :ids, :division_id, :division_type, :name, :month
    attr_writer :from_date, :to_date

    def search
      ret = ::Record.includes(:person).includes(:division).joins(:division)
      ret = ret.where(id: ids) if ids.present?
      ret = ret.where(person_id: name) if name.present?
      ret = ret.where(divisions: {type: division_type}) if division_type.present?
      ret = ret.where(division_id: division_id) if division_id.present?
      ret = ret.where(date: date) if date.present?
      ret = ret.where(date: days_of_month) if month.present?
      ret.order(date: :desc)
    end

    def from_date
      Date.parse(@from_date.to_s)
    rescue TypeError, Date::Error
      nil
    end

    def to_date
      Date.parse(@to_date.to_s)
    rescue TypeError, Date::Error
      nil
    end

    def date
      return if from_date.nil? && to_date.nil?

      from_date..to_date
    end

    def days_of_month
      start_day = Date.strptime(month, '%Y-%m')
      end_day = start_day.end_of_month
      start_day..end_day
    end
  end
end

app/controllers/records_controller.rb
# frozen_string_literal: true

class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]
  before_action -> {require_data(records_url, Person)},
                only: [:new, :create, :edit, :update]
  before_action :check_csv, only: :load_csv

  def index
    @record = Search::Record.new
    @records = @record.search.paginate(params)
  end

  def search
    @record = Search::Record.new(search_params)
    @records = @record.search.paginate(params)
  end

  def show
  end

  def new
    @record = Record.new(record_params_for_continue)
  end

  def edit
  end

  def create
    @record = Record.new(record_params)

    respond_to do |format|
      notices = []
      if (ret = @record.create_self_and_transports)
        notices << t('helpers.notice.create')
        notices << t('helpers.notice.transport_created') if ret.size > 1
        if params[:continuous].present?
          notices << t('helpers.notice.continuously_create')
          format.html {redirect_to new_record_url(record: record_params), notice: notices}
        end
        format.html {redirect_to records_url, notice: notices}
      else
        format.html {render :new, status: :unprocessable_content}
        format.json {render json: @record.errors, status: :unprocessable_content}
      end
    end
  end

  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html {redirect_to records_url, notice: t('helpers.notice.update')}
      else
        format.html {render :edit, status: :unprocessable_content}
        format.json {render json: @record.errors, status: :unprocessable_content}
      end
    end
  end

  def destroy
    @record.destroy
    respond_to do |format|
      format.html {redirect_to records_url, notice: t('helpers.notice.delete'), status: :see_other}
      format.json {head :no_content}
    end
  end

  def export
    encoding = params[:export][:encoding]
    filename = "record_#{Time.current.strftime('%Y%m%d%H%M%S')}.csv"
    record = Search::Record.new(export_params)
    records = record.search
    csv_data = RecordCSV.export(records, encoding)
    send_data csv_data, filename: filename, type: 'text/csv'
  end

  def load_csv
    @record_csv = RecordCSV.load(@csv_path)
    render :import
  rescue ArgumentError => e
    Rails.logger.info("ERROR: #{e}")
    redirect_to search_records_url, alert: e.message
  end

  private

  def set_record
    @record = Record.find(params[:id])
  end

  def record_params
    params.expect(record: [:cost, :date, :person_id, :division_id])
  end

  def record_params_for_continue
    params[:record]&.permit(:cost, :date, :person_id, :division_id)
  end

  def search_params
    permitted = [
      :name, :division_id, :division_type, :from_date, :to_date, :month
    ]
    params.fetch(:search_record, {}).permit(permitted)
  end

  def export_params
    params.expect(export: [{ids: []}])
  end

  def check_csv
    file = params.dig(:load_csv, :file)
    if file.respond_to?(:path)
      @csv_path = file.path
      return if File.extname(@csv_path) == '.csv'
    end

    redirect_to search_records_url, notice: t('helpers.notice.load_csv.invalid_format')
  end
end

app/helpers/records_helper.rb
# frozen_string_literal: true

module RecordsHelper
  def render_division(division)
    emoji = case division
            when Drugstore
              ':pill:'
            when Transport
              ':train:'
            when Hospital
              ':hospital:'
            end
    [emoji, division.model_name.human].join
  end
end

app/views/records/_division_name.html.erb
<%= select_tag "#{name}[division_id]", options_for_select(objects),
               include_blank: true, class: 'form-control', disabled: objects.blank? %>

app/views/records/_export.html.erb
<%= form_tag(export_records_path, method: :get) do %>
  <div class="container box_radius">
    <div class="row">
      <div class="col-4">
        <%= select_tag 'export[encoding]',
                       options_for_select('UTF-8' => 'utf-8', 'Shift-JIS' => 'sjis'),
                       class: 'form-control form-select' %>
        <% records.each do |record| %>
          <%= hidden_field_tag 'export[ids][]', record.id %>
        <% end %>
      </div>
      <div class="col-2">
        <%= submit_tag t('helpers.submit.export_csv'), class: 'btn btn-success', name: nil, data: {disable_with: false} %>
      </div>
    </div>
  </div>
<% end %>

app/views/records/_form.html.erb
<%= form_with(model: record, local: true) do |form| %>
  <% if record.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% record.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row mb-3">
      <div class="col-5 col-md-2">
        <%= form.label :date %>
      </div>
      <div class="col-7 col-md-10">
        <div class="input-group date-picker" data-wrap="true">
          <%= form.text_field :date, class: 'form-control', data: {input: true}, required: true %>
          <div class="input-group-text fa-icon" data-toggle>
            <span class="fa fa-calendar"></span>
          </div>
        </div>
      </div>
    </div>
    <div class="row mb-3">
      <div class="col-5 col-md-2">
        <%= form.label :person_id, Person.human_attribute_name(:name) %>
      </div>
      <div class="col-7 col-md-10">
        <%= form.collection_select :person_id, Person.all, :id, :name,
                                   {include_blank: true},
                                   class: 'form-control form-select', required: true %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-5 col-md-2">
        <%= form.label :division_type, Division.model_name.human %>
      </div>
      <div class="col-7 col-md-10">
        <%= form.select :division_type, Division.division_names.invert,
                        {include_blank: true,
                         selected: record.division&.model_name},
                        class: 'form-control form-select division_type', required: true %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-5 col-md-2">
        <%= form.label :division_id, Division.human_attribute_name(:name) %>
      </div>
      <div class="col-7 col-md-10">
        <% records = Division.all_records(record.division_type) %>
        <%= form.select :division_id, records.map {|r| [r.name, r.id]}, {include_blank: true},
                        class: 'form-control form-select', id: 'division-id-select',
                        disabled: records.blank?, required: true %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-5 col-md-2">
        <%= form.label :cost %>
      </div>
      <div class="col-7 col-md-10">
        <%= form.number_field :cost, class: 'form-control', min: 0, required: true %>
      </div>
    </div>

    <% if controller.action_name == 'new' %>
      <div class="row mb-3">
        <div class="input-group col-5">
          <div class="input-group-text">
            <%= check_box_tag :continuous, class: 'checkbox' %>
          </div>
          <%= label_tag :continuous, t('helpers.label.continuously_create'), class: 'form-control' %>
        </div>
      </div>
    <% end %>
    <div class="actions">
      <%= form.submit class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/records/_load_csv.html.erb
<%= form_tag(load_csv_records_path, method: :put, multipart: true) do %>
  <div class="container box_radius">
    <div class="row">
      <div class="col-8 col-md-5">
        <%= file_field_tag 'load_csv[file]', class: 'form-control-file', id: 'csv_loader', accept: '.csv' %>
      </div>
      <div class="col-4 col-md-2">
        <%= submit_tag t('helpers.submit.load_csv'),
                       class: 'btn btn-success', name: nil, disabled: true, id: :csv_load_button %>
      </div>
    </div>
  </div>
<% end %>

app/views/records/_load_csv_result.html.erb
<table class='table table-bordered table-hover table-striped'>
  <thead>
  <tr>
    <th>正常</th>
    <th><%= Record.human_attribute_name :date %></th>
    <th><%= Person.human_attribute_name :name %></th>
    <th><%= Division.model_name.human %></th>
    <th><%= Division.human_attribute_name :name %></th>
    <th><%= Record.human_attribute_name :cost %></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% records.each do |record| %>
    <tr>
      <td><%= record.valid? ? '○' : '×' %></td>
      <td><%= record.date %></td>
      <td><%= record.person_name %></td>
      <td><%= record.division %></td>
      <td><%= record.division_name %></td>
      <td><%= record.cost %></td>
      <td><%= t('helpers.link.delete') %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/records/_search.html.erb
<%= form_with(model: record, url: search_records_path, method: :get, local: true, id: :search_record_form) do |form| %>
  <button class="btn btn-primary" type="button" data-bs-toggle="collapse"
          data-bs-target="#collapseSearch" aria-expanded="true" aria-controls="collapseSearch">
    <%= t('helpers.button.search_form') %>
  </button>
  <div class="container collapse show box_radius" id="collapseSearch">
    <div class="row">
      <div class="col-2">
        <%= form.label :from_date, Record.human_attribute_name(:date) %>
      </div>
      <div class="col-8 col-md-4">
        <div class="input-group date-picker" data-wrap="true">
          <%= form.text_field :from_date, class: 'form-control', data: {input: true} %>
          <div class="input-group-text fa-icon" data-toggle>
            <span class="fa fa-calendar"></span>
          </div>
          <div class="input-group-text fa-icon" data-clear>
            <span class="fa fa-times"></span>
          </div>
        </div>
      </div>
      <div class="col-1 text-center">～</div>
      <div class="col-8 offset-2 col-md-4 offset-md-0 mb-3">
        <div class="input-group date-picker" data-wrap="true">
          <%= form.text_field :to_date, class: 'form-control', data: {input: true} %>
          <div class="input-group-text fa-icon" data-toggle>
            <span class="fa fa-calendar"></span>
          </div>
          <div class="input-group-text fa-icon" data-clear>
            <span class="fa fa-times"></span>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-2 col-md-2">
        <%= form.label :month, t('datetime.prompts.month') %>
      </div>
      <div class="col-8 col-md-4 mb-3">
        <div class="input-group month-picker" data-wrap="true">
          <%= form.text_field :month, class: 'form-control', data: {input: true} %>
          <div class="input-group-text fa-icon" data-toggle>
            <span class="fa fa-calendar"></span>
          </div>
          <div class="input-group-text fa-icon" data-clear>
            <span class="fa fa-times"></span>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-2 col-4">
        <%= form.label :name, Person.human_attribute_name(:name) %>
      </div>
      <div class="col-lg-2 col-8 mb-3">
        <%= form.collection_select :name, Person.all, :id, :name,
                                   {include_blank: true}, class: 'form-control form-select' %>
      </div>
      <div class="col-lg-2 col-4">
        <%= form.label :division_type, Division.model_name.human %>
      </div>
      <div class="col-lg-2 col-8 mb-3">
        <%= form.select :division_type, Division.division_names.invert,
                        {include_blank: true}, class: 'form-control form-select division_type' %>
      </div>
      <div class="col-lg-2 col-4">
        <%= form.label :division_name, Division.human_attribute_name(:name) %>
      </div>
      <div class="col-lg-2 col-8 mb-3">
        <% records = Division.all_records(record.division_type) %>
        <%= form.select :division_id, records.map {|r| [r.name, r.id]},
                        {include_blank: true},
                        class: 'form-control form-select', id: 'division-id-select', disabled: records.blank? %>
      </div>
    </div>
    <%= button_tag t('helpers.button.reset'), type: :button, id: 'reset_search', class: 'btn btn-secondary' %>
    <%= form.submit t('helpers.submit.search'), class: 'btn btn-success', name: nil %>
  </div>
<% end %>

app/views/records/_search_result.html.erb
<%= paginate records %>
<table class='table table-bordered table-hover table-striped'>
  <thead>
  <tr>
    <th><%= Record.human_attribute_name :date %></th>
    <th><%= Person.human_attribute_name :name %></th>
    <th><%= Division.model_name.human %></th>
    <th><%= Division.human_attribute_name :name %></th>
    <th><%= Record.human_attribute_name :cost %></th>
  </tr>
  </thead>

  <tbody>
  <% records.each do |r| %>
    <tr>
      <td><%= link_to l(r.date), record_path(r) %></td>
      <td><%= tag.span r.person.name %></td>
      <td><%= tag.span render_division(r.division), class: 'emojify' %></td>
      <td><%= tag.span r.division.name %></td>
      <td><%= tag.span r.cost.to_fs(:currency) %></td>
    </tr>
  <% end %>
  </tbody>

  <tfoot>
  <% if controller.action_name == 'search' %>
    <tr>
      <th colspan="4"><%= t('text.records.total') %></th>
      <th><%= records.except(:limit, :offset).pluck(:cost).sum.to_fs(:currency) %></th>
    </tr>
  <% end %>
  </tfoot>
</table>
<%= paginate records %>

app/views/records/edit.html.erb
<h1>
  <%= t('helpers.title.edit', model: Record.model_name.human) %>
</h1>

<%= render partial: 'partials/action' %>

<%= render 'form', record: @record %>

app/views/records/import.html.erb
<h1>
  <%= t('helpers.title.load_csv', models: Record.model_name.human.pluralize(I18n.locale)) %>
</h1>

<%= render partial: 'load_csv_result', locals: {records: @record_csv} %>

app/views/records/index.html.erb
<h1>
  <%= t('helpers.title.list', models: Record.model_name.human.pluralize(I18n.locale)) %>
</h1>

<%= link_to t('helpers.link.new'), new_record_path %>

<%= render partial: 'search_result', locals: {records: @records} %>

<br>

<%= link_to t('helpers.link.new'), new_record_path %>

app/views/records/new.html.erb
<h1>
  <%= t('helpers.title.new', model: Record.model_name.human) %>
</h1>

<%= render partial: 'partials/action' %>

<%= render 'form', record: @record %>

app/views/records/search.html.erb
<h1>
  <%= t('helpers.title.search', models: Record.model_name.human.pluralize(I18n.locale)) %>
</h1>

<%= render partial: 'search', locals: {record: @record} %>
<%#= render partial: 'export', locals: {records: @records} %>
<%#= render partial: 'load_csv' %>

<br>

<%= render partial: 'search_result', locals: {records: @records} %>

<br>

app/views/records/show.html.erb
<h1>
  <%= t('helpers.title.show', model: Record.model_name.human) %>
</h1>

<%= render partial: 'partials/action' %>

<div class="container">
  <div class="row">
    <div class="col-4 col-sm-2">
      <%= Record.human_attribute_name :date %>
    </div>
    <div class="col-8 col-sm-10">
      <%= l(@record.date) %>
    </div>
  </div>
  <div class="row">
    <div class="col-4 col-sm-2">
      <%= Person.human_attribute_name :name %>
    </div>
    <div class="col-8 col-sm-10">
      <%= @record.person.name %>
    </div>
  </div>
  <div class="row">
    <div class="col-4 col-sm-2">
      <%= Division.model_name.human %>
    </div>
    <div class="col-8 col-sm-10 emojify">
      <%= render_division(@record.division) %>
    </div>
  </div>
  <div class="row">
    <div class="col-4 col-sm-2">
      <%= Division.human_attribute_name :name %>
    </div>
    <div class="col-8 col-sm-10">
      <%= @record.division.name %>
    </div>
  </div>
  <div class="row">
    <div class="col-4 col-sm-2">
      <%= Record.human_attribute_name :cost %>
    </div>
    <div class="col-8 col-sm-10">
      <%= @record.cost.to_fs(:currency) %>
    </div>
  </div>
</div>